### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by hairullana** [CPJKU/onset_detection#2]
![image](https://user-images.githubusercontent.com/56705867/155448442-c44e5d62-1f56-47d4-9cb7-2619d7658854.png)

 File "onset_program.py", line 759
    print args
    ^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by superbock** [comment]
This code is very old and thus not supported any more. It won't be ported to Python 3.
However, you can fix this quite easily yourself by adding parentheses as indicated by the error message.

Most methods are implemented in [madmom](https://github.com/cpjku/madmom) anyways, please refer to the `madmom.features.onsets` module.
